spring: 

  datasource:
    url: jdbc:h2:mem:product
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
 
  
#  datasource:
#    url: jdbc:oracle:thin:@localhost:1521:xe
#    username: system
#    password: sirisha
#    driver-class-name: oracle.jdbc.OracleDriver
#  jpa:
#    show-sql: true
#    hibernate:
#      ddl-auto: update
  application:
    name: PRODUCT-SERVICE
#  zipkin:
#    base-url: http://127.0.0.1:9411/

  config:
    import: configserver:http://${CONFIG_SERVER_URL:localhost}:8064
      
      
  
#eureka:
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka/}
#  instance:
#    hostname: localhost
#okta:
#  oauth2:
#    issuer: https://dev-20277398.okta.com/oauth2/default
#    audience: api://default
#  