spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Rajeshgottimukkula/configserver
          clone-on-start: true  
          
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}
      